### ISSUE TITLE
Latest changes in BSP makes build fail

### ISSUE THREAD

**Issue by sruehl** [compulab-yokneam/meta-mender-compulab#5]
@vraevsky apparently due to changes in https://github.com/compulab-yokneam/meta-compulab-bsp the build doesn't work anymore:

`export MACHINE=iot-gate-imx8`
`source compulab-setup-env build`

```
ERROR: The following layer directories do not exist:
ERROR:    /builddir/sources/meta-compulab-som
ERROR:    /builddir/sources/meta-fslc-som
ERROR:    /builddir/sources/meta-fslc-som-common
```

**Comment by vraevsky** [comment]
@sruehl , thanks for reporting on the issue.
The updated layer resored back https://github.com/compulab-yokneam/compulab-fslc-bsp/commits/master.
Sorry for that inconvenience.

**Comment by sruehl** [comment]
Thanks for fixing it that fast... Seems everything is working now just fine :)
