### ISSUE TITLE
how to `mr-deploy` after done once

### ISSUE THREAD

**Issue by arrow53** [compulab-yokneam/meta-mender-compulab#6]
I know normally mender would be doing updates. But, if I want to reflash with a new image and have flashed before, holding down the button on the UCM board and trying to boot off the SD card doesn't work. With a `mr-deploy` I get this

```
root@ucm-imx8m-plus:~# mr-deploy                                                
Invalid DST=/dev/mmcblk2 is equal to BOOT=/dev/mmcblk2, exiting with errno=3
```

**Comment by vraevsky** [comment]
https://github.com/compulab-yokneam/Documentation/blob/master/etc/mender.adoc#reflash-a-new-mender-image-on-an-early-flashed-mender-media

**Comment by arrow53** [comment]
ah, thanks!
