### ISSUE TITLE
ETA for Kirkstone support

### ISSUE THREAD

**Issue by sruehl** [compulab-yokneam/meta-mender-compulab#7]
Kirkstone released this may https://wiki.yoctoproject.org/wiki/Releases.

Is there any ETA when this layer support that release?

**Comment by akash-roboticist** [comment]
+1 for Kirkstone support.

It looks like [kirkstone](https://github.com/compulab-yokneam/meta-mender-compulab/tree/kirkstone) was branched by @vraevsky and is WIP. Would be happy to test and provide feedback if that helps.

**Comment by vraevsky** [comment]
> Kirkstone released this may https://wiki.yoctoproject.org/wiki/Releases.
> 
> Is there any ETA when this layer support that release?

What machine support do you need?

**Comment by akash-roboticist** [comment]
Mender support for `iot-gate-imx8`; I see branch was updated yesterday, will give it a try...

**Comment by akash-roboticist** [comment]
The scripts need some updating @vraevsky ; I guess firstly needs fixing of https://github.com/compulab-yokneam/compulab-fslc-bsp/issues/1 and then trying out a build to see what else needs updates...

**Comment by sruehl** [comment]
for me iot-gate-imx8 too

**Comment by sruehl** [comment]
@akash-roboticist does it build now for you as https://github.com/compulab-yokneam/compulab-fslc-bsp/issues/1 is fixed now? Didn't try it yet

**Comment by akash-roboticist** [comment]
Image build succeeded,  haven't tested it yet though.

**Comment by akash-roboticist** [comment]
@vraevsky the image built fine, but it looks like im running into an odd issue deploying it -
The USB flash drive I am using  to flash the initial image seems to exceed the 16GB emmc on the `iot-gate-imx8` by a few MBs so `mr-deploy` fails. I tried editing the `/data` partition on the flash drive to make sure it fits within the sector limits of the emmc, but that didnt work either as the script seems to check the entire `/dev/sda` size against the mmc.

I tried the pre-built image listed on the README, and had the same issue with it too.

**Comment by vraevsky** [comment]
We are using uuu for deploying it onto the internal media.
The mr-deploy fix will be provided latter.

**Comment by akash-roboticist** [comment]
Can you share the steps please? @vraevsky

**Comment by vraevsky** [comment]
The mr-deploy issue has been solved. The pre-built image is fixed as well.

**Comment by akash-roboticist** [comment]
Just tried the pre-built image as well as building from source; it does not boot with that image from the flash drive with either of these and gets stuck on `Starting Kernel...`
Probably a dtb is missing? @vraevsky

**Comment by vraevsky** [comment]
> Just tried the pre-built image as well as building from source; it does not boot with that image from the flash drive with either of these and gets stuck on `Starting Kernel...` Probably a dtb is missing? @vraevsky

Please provide the logs; moreover pleas issue these sequence in U-boot and post the output:
usb reset
mmc list
ls usb 0
ls mmc 2

br @vraevsky

**Comment by akash-roboticist** [comment]
**Debug logs as requested**
```
IOT-GATE-iMX8 => usb reset
resetting USB...
Bus usb@32e40000: USB EHCI 1.00
Bus usb@32e50000: USB EHCI 1.00
scanning bus usb@32e40000 for devices... 1 USB Device(s) found
scanning bus usb@32e50000 for devices... 5 USB Device(s) found
       scanning usb for storage devices... 1 Storage Device(s) found
```
```
IOT-GATE-iMX8 => mmc list
FSL_SDHC: 2 (eMMC)
```
```
IOT-GATE-iMX8 => ls usb 0
     1378   boot.scr
            grub-mender-grubenv/
            dtb/
    41599   sb-iotgimx8.dtb
    42123   sb-iotgimx8-poedv2.dtb
   491160   tee.bin
    44903   sb-iotgimx8-ied.dtb
    45657   sb-iotgimx8-ied-m4.dtb
            EFI/
    45525   sb-iotgimx8-ied-wakeup.dtb
    43449   sb-iotgimx8-can.dtb
    42257   sb-iotgimx8-poed.dtb
    37528   ucm-imx8m-mini.dtb
 26694144   Image

11 file(s), 3 dir(s)
```
```
IOT-GATE-iMX8 => ls mmc 2
            EFI/
 23155200   Image
     1167   boot.scr
            dtb/
    40893   sb-iotgimx8-can.dtb
    42889   sb-iotgimx8-ied-m4.dtb
    43048   sb-iotgimx8-ied-wakeup.dtb
    42426   sb-iotgimx8-ied.dtb
    39701   sb-iotgimx8-poed.dtb
    39567   sb-iotgimx8-poedv2.dtb
    39043   sb-iotgimx8.dtb
    35226   ucm-imx8m-mini.dtb

10 file(s), 2 dir(s)
```

**Boot logs , for booting kirkstone usb flash drive**
```
IOT-GATE-iMX8 => setenv script; boot;
Trying to boot from SD ...
Can't set block device
Can't set block device
Trying to boot from USB ...
resetting USB...
Bus usb@32e40000: USB EHCI 1.00
Bus usb@32e50000: USB EHCI 1.00
scanning bus usb@32e40000 for devices... 1 USB Device(s) found
scanning bus usb@32e50000 for devices... 5 USB Device(s) found
       scanning usb for storage devices... 1 Storage Device(s) found
** No boot file defined **
26694144 bytes read in 1062 ms (24 MiB/s)
41599 bytes read in 4 ms (9.9 MiB/s)
Booting from USB script ...
Moving Image from 0x40480000 to 0x40600000, end=42090000
## Flattened Device Tree blob at 43000000
   Booting using the fdt blob at 0x43000000
   Using Device Tree in place at 0000000043000000, end 000000004300d27e
Modify /vpu_g1@38300000:status disabled
Modify /vpu_g2@38310000:status disabled
Modify /vpu_h1@38320000:status disabled

Starting kernel ...
```

@vraevsky ^ as requested.

**Comment by akash-roboticist** [comment]
@vraevsky any insights?

**Comment by vraevsky** [comment]
Already fixed.
