### ISSUE TITLE
Example build has multiple errors

### ISSUE THREAD

**Issue by daysave-jeikki** [compulab-yokneam/meta-mender-compulab#9]
Following the instructions in README and building the example image without any modifications has two errors and multiple warnings. Someone with more experience could maybe check these out. I'm new to Yocto and not sure what I'm doing. Thanks!

In order to create succesful build I needed make following changes:

- Remove `0001-attestation-test-Avoid-asserts.patch` from `optee-imx` recipe
- Remove `sources/meta-compulab-bsp/meta-multimedia/recipes-nnstreamer/nnshark/nnshark_%.bbappend` file

**Comment by vraevsky** [comment]
Hi @daysave-jeikki ,

Thanks for reporting on the issues. The fixes are allready provided:
optee-imx)
https://github.com/compulab-yokneam/meta-bsp-imx8mm/commit/d42d76a542bfafaf72e74f5a8ec8daa312e0bafa
nnshark)
https://github.com/compulab-yokneam/meta-mender-compulab/commit/83ad9fcbac6c0a46118e22c9995a72c11efc0234
